name: laravel-benchmark-roadrunner

services:
  app:
    build:
      context: ../..
      dockerfile: runtimes/roadrunner/Dockerfile
    ports:
      - "8084:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr
      OCTANE_SERVER: roadrunner
